name: kolo_purse
description: A simple login and sign-in with mock up API


publish_to: 'none' 


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.7
  flutter_svg: ^0.22.0
  provider: ^5.0.0
  http: ^0.12.2


  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Qs
      fonts:
        - asset: assets/images/kolopurse-logo.svg
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
